- name: variables from promt
  hosts: local
  connection: local
  vars_promt: 
  - name: username
    prompt: what is your name
    private: false
 tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "hello,username is:{{ username }}"
